### ISSUE TITLE
add C long type

### ISSUE THREAD

**Issue by Sinfolke** [ASDAlexander77/TypeScriptCompilerDefaultLib#1]
there's no long long and long double type (maybe since spaces aren't allowed in ts). I could suggest use the following:
llong and long_long for long long, ullong and ulong_long for unsigned long long (or a size_t instead)
ldouble and long_double for long_double
uchar for unsigned char

```ts
declare type byte = number;
declare type short = number; 
declare type ushort = number;
declare type int = number;
declare type uint = number;
declare type long = number;
declare type ulong = number;
declare type llong = number;     // long long
declare type long_long = number; // long long
declare type ullong = number;     // unsigned long long
declare type ulong_long = number; // unsigned long long 
declare type char = number;
declare type uchar = number;     // unsigned char
declare type i16 = number;
declare type i32 = number;
declare type i64 = number;
declare type u16 = number;
declare type u32 = number;
declare type u64 = number;
declare type f16 = number;
declare type f32 = number;
declare type f64 = number;
declare type f128 = number;
declare type half = number;
declare type float = number;
declare type double = number;
declare type ldouble = number; // long double
declare type long_double = number; // long double
```

**Comment by ASDAlexander77** [comment]
I have list of aliases for native types:

            byte
            short
            ushort
            int
            uint
            long
            ulong
            char
            i8
            i16
            i32
            i64
            u8
            u16
            u32
            u64
            s8
            s16
            s32
            s64
            f16
            f32
            f64
            f128
            half
            float
            double
--------------
```ulong``` & ```long``` is ```long long``` and ```unsigned long long``` in c++
